[project]
name = "almanac"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.13"
dependencies = [
    "opencv-python>=4.12.0.88",
    "pyautogui>=0.9.54",
]
